apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tektoncd-results-zrij
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tektoncd-results-zrij
    app.kubernetes.io/part-of: tekton-results
  name: tektoncd-results-zrij
  namespace: rh-ee-mmhedhbi-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: tektoncd-results-zrij
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: tektoncd-results-zrij
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:zIbdV-tektoncd-results-zrij
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
