apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tektoncd-results-zrij
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tektoncd-results-zrij
    app.kubernetes.io/part-of: tekton-results
  name: tektoncd-results-zrij
  namespace: rh-ee-mmhedhbi-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: tektoncd-results-zrij
    weight: null
status: {}
